"""created tables with indexes and triggers

Revision ID: 370c307c99c5
Revises: 
Create Date: 2025-12-21 15:47:53.367179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370c307c99c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('video_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_creator_id'), 'videos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_videos_video_created_at'), 'videos', ['video_created_at'], unique=False)
    op.create_index(op.f('ix_videos_views_count'), 'videos', ['views_count'], unique=False)
    op.create_table('video_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('delta_views_count', sa.Integer(), nullable=False),
    sa.Column('delta_likes_count', sa.Integer(), nullable=False),
    sa.Column('delta_comments_count', sa.Integer(), nullable=False),
    sa.Column('delta_reports_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_snapshots_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_snapshots'))
    )
    op.create_index(op.f('ix_video_snapshots_created_at'), 'video_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_snapshots_delta_views_count'), 'video_snapshots', ['delta_views_count'], unique=False)
    op.create_index(op.f('ix_video_snapshots_video_id'), 'video_snapshots', ['video_id'], unique=False)
    
    # Manually created function for auto-updating updated_at timestamp
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # trigger for videos tables
    op.execute("""
        CREATE TRIGGER update_videos_updated_at
        BEFORE UPDATE ON videos
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    
    # triggers for video_snapshots table
    op.execute("""
        CREATE TRIGGER update_video_snapshots_updated_at
        BEFORE UPDATE ON video_snapshots
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop triggers and function
    op.execute("DROP TRIGGER IF EXISTS update_video_snapshots_updated_at ON video_snapshots;")
    op.execute("DROP TRIGGER IF EXISTS update_videos_updated_at ON videos;")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
   
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_snapshots_video_id'), table_name='video_snapshots')
    op.drop_index(op.f('ix_video_snapshots_delta_views_count'), table_name='video_snapshots')
    op.drop_index(op.f('ix_video_snapshots_created_at'), table_name='video_snapshots')
    op.drop_table('video_snapshots')
    op.drop_index(op.f('ix_videos_views_count'), table_name='videos')
    op.drop_index(op.f('ix_videos_video_created_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_creator_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
